### ISSUE TITLE
Error when running download.py

### ISSUE THREAD

**Issue by Rhys-McAlister** [5uru/Median#19]
When running the download.py file I get the following error:

`Fetching 7 files: 100%|██████████████████████████| 7/7 [00:00<00:00, 41883.21it/s]

✘ No compatible package found for 'en_core_news_sm' (spaCy v3.7.4)`

**Comment by 5uru** [comment]
Hi
I've just corrected the error. Thank you very much.

**Comment by Rhys-McAlister** [comment]
Noworries
