### ISSUE TITLE
Error when generating new flashcards 

### ISSUE THREAD

**Issue by Rhys-McAlister** [5uru/Median#23]
When attempting to generate new flashcards using the streamlit ui I get the following error:

`Generate the output in the specified format, basing the output strictly on the provided corpus and the identified themes. If there is no relevant information in the corpus, return 'None' for the corresponding field. Remember to use the following schema for the output:

{
    "collection": [
    {
    "question": "string",
      "answer": "string"
    }
  ]
}
<|END_OF_TURN_TOKEN|>
     
libc++abi: terminating due to uncaught exception of type std::runtime_error: [METAL] Command buffer execution failed: Insufficient Memory (00000008:kIOGPUCommandBufferCallbackErrorOutOfMemory)
zsh: abort      streamlit run Flashcards.py
(med) (.conda) (base) rhysmcalister@Rhyss-MacBook-Air-2 Median %        streamlit run Flashcards.py/Users/rhysmcalister/miniconda3/envs/med/lib/python3.11/multiprocessing/resource_tracker.py:254: UserWarning: resource_tracker: There appear to be 1 leaked semaphore objects to clean up at shutdown
  warnings.warn('resource_tracker: There appear to be %d '`

I'm running this on an 8 gb MacBook Air so this might be the cause

**Comment by 5uru** [comment]
Yes exactly, I've been using the mistral V2 model, which needs a bit more memory, but I'm currently looking for a smaller model that would be just as effective. 
I'm really sorry and you can also send me some small models that you have already used so that I can test them.
